Controllers/comensal/ComensalController.cs
using ekitchen.Entidades.EF;
using ekitchen.Models.ComensalesModel;
using ekitchen.Models.ComentariosModel;
using ekitchen.Models.Mappings;
using ekitchen.Servicios.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ekitchen.Controllers.comensal
{
    public class ComensalController : Controller
    {
        private IReservaServicio _ServicioReserva;
        private IEventoServicio _ServicioEvento;
        private ICalificacioneServicio _ServicioCalificacione;
        public ComensalController(IReservaServicio ServicioReserva, IEventoServicio servicioEvento, ICalificacioneServicio servicioCalificacione)
        {
            _ServicioReserva = ServicioReserva;
            _ServicioEvento = servicioEvento;
            _ServicioCalificacione = servicioCalificacione;
        }

        public Boolean puedeInjectar()
        {
            if (HttpContext.Session.GetInt32("IdUsuario") != null &&
               HttpContext.Session.GetInt32("Perfil") == 2)
            {
                return true;
            }
            return false;

        }

        public IActionResult Index()
        {
            if (puedeInjectar())
            {
                int idComensal = (int)HttpContext.Session.GetInt32("IdUsuario");
                List<Evento> EventosComensal = _ServicioReserva.ObtenerMisReservasPorId(idComensal);
                List<EventoComentarioModel> EventosComentarios = EventosComensal.EventoToEventoComentarioModel();
                return View(EventosComentarios);
            }
            else
            {
                return View("InjectionCocineroError");
            }
        }

     
        
        public IActionResult Reserva()
        {
            if (puedeInjectar())
            {
                return View(_ServicioReserva.EventosDisponibles());
            }
            else
            {
                return View("InjectionCocineroError");
            }
        }

        [HttpGet]
        [Route("Comensal/Reservar/{idEvento}")]
        public IActionResult Reserva(int idEvento)
        {
            if (puedeInjectar())
            {
                ReservaModel reservaModel = new ReservaModel();
                // Obtiene lista de recetas del evento
                List<Receta> listaRecetas = _ServicioReserva.obtenerEventoPorId(idEvento);
                // Mapea las recetas al model de receta de Comensal
                List<ComensalRecetaOpcionModel> recetas = listaRecetas.RecetaToComensalRecetaOpcionModel();
                // Setea la lista de recetas model de comensal para el formulario
                ViewBag.ListaRecetas = recetas;
                reservaModel.IdEvento = idEvento;

                return View("EventoAReservar", reservaModel);
            }
            else
            {
                return View("InjectionCocineroError");
            }
        }

        public IActionResult GuardarReserva(ReservaModel reservaModel)
        {
            if (puedeInjectar())
            {
                int idComensal = (int)HttpContext.Session.GetInt32("IdUsuario");
                Boolean registro=_ServicioReserva.registrarReserva(reservaModel.IdEvento, idComensal, reservaModel.RecetaSeleccionada, reservaModel.CantidadComensales);
                if (registro)
                {
                    TempData["Reseva"] = "Reserva realizada con éxito";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Error"] = "La cantidad de comensales que indicaste supera la capacidad que tenemos";
                    return RedirectToAction("Reserva");
                }
            }
            else
            {
                return View("InjectionCocineroError");
            }
        }

        //este vendria hacer donde si entras a mis comentarios te muestra los comentarios que hiciste//
       public IActionResult Comentarios()
        {
            if (puedeInjectar())
            {
                int idComensal = (int)HttpContext.Session.GetInt32("IdUsuario");
                //aqui tuve que buscar los eventos y las calificaciones para poder recorrerlos//
                //y rellenar la informacion de todos los eventos que comento//
                ViewBag.Evento = _ServicioReserva.ObtenerMisReservasPorId(idComensal);
                return View("IndexComentarios", _ServicioCalificacione.obtenerMisCalificaciones(idComensal));
            }
            else
            {
                return View("InjectionCocineroError");
            }

        }

        //aqui te direcciona cuando desde la vista de mis reservas queres comentar//
        [HttpGet]
        [Route("Comensal/Comentar/{idEvento}")]
        public IActionResult Comentar(int idEvento)
        {
            if (puedeInjectar())
            {
                int IdComensal = (int)HttpContext.Session.GetInt32("IdUsuario");

                ViewBag.idevento = idEvento;
                return View("Comentarios");
            }
            else
            {
                return View("InjectionCocineroError");
            }
        }


        //aqui es donde se llama al metodo para guardar el comentario de dicho evento
        [HttpPost]
        public IActionResult Comentario(ComentarioModel comentarioModel)
        {
            if (puedeInjectar())
            {
                if (ModelState.IsValid)
                {
                    int idComensal = (int)HttpContext.Session.GetInt32("IdUsuario");
                    Calificacione comentario = comentarioModel.ComentariosModelToCalificacione(idComensal);
                    if (_ServicioCalificacione.RegistrarCalificacion(comentario) == true)
                    {
                        @TempData["ComentarioCreado"] ="Comentario guardado";
                        return RedirectToAction("Comentarios");
                    }
                    else
                    {
                        return RedirectToAction("Comentar", comentario.IdEvento);
                    }
                }
                else
                {
                    return RedirectToAction("Comentar", comentarioModel.IdEvento);
                }
            }
            else
            {
                return View("InjectionCocineroError");
            }
        }

    }
}

Controllers/default/DefaultController.cs
using ekitchen.Entidades.Dishes;
using ekitchen.Entidades.EF;
using ekitchen.Models.EventosModel;
using ekitchen.Models.Mappings;
using ekitchen.Servicios.Dishes;
using ekitchen.Servicios.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;


namespace ekitchen.Controllers.inicio
{

    public class DefaultController : Controller
    {
        //private readonly ILogger<InicioController> _logger;
        private readonly IWebHostEnvironment _appEnvironment;
        private IEventoServicio _eventoServicio;
        private ICalificacioneServicio _calificacioneServicio;
        
        public DefaultController(IWebHostEnvironment appEnvironment, IEventoServicio eventoServicio, ICalificacioneServicio calificacioneServicio)
        {
            _appEnvironment = appEnvironment;
            _eventoServicio = eventoServicio;
            _calificacioneServicio = calificacioneServicio;
        }

        public IActionResult Index()
        {
            
          //  var client = new RestClient("https://localhost:44315/Evento/EventosConComentarios");
          //  client.Timeout = -1;
          //  var request = new RestRequest(Method.GET);
          //  var body = @"";
          //  request.AddParameter("text/plain", body, ParameterType.RequestBody);
          //  IRestResponse response = client.Execute(request);
          //  var lista = JsonConvert.DeserializeObject<List<Evento>>(response.Content);
            List<Evento> ListaEventos = _eventoServicio.ObtenerEventosFinalizadosConComentarios();
            List<EventoPuntuacionModel> eventoPuntuacionModels = ListaEventos.ListaEventosToListaEventoPuntuacionModel();
            return View(eventoPuntuacionModels);
        }

        public IActionResult DetalleEvento(int IdEvento)
        {
            Evento evento = _eventoServicio.ObtenerEventoPorId(IdEvento);
            Usuario usuario = _eventoServicio.ObtenerCocineroPorId(evento.IdCocinero);
            List<Calificacione> calificaciones = _calificacioneServicio.ObtenerCalificacionesPorIdEvento(IdEvento);

            EventoDetalle eventoDetalles = MetodosExtendidos.BuildEventoDetalleModel(evento, usuario, calificaciones);
            return View(eventoDetalles);
        }

       
    }
}

Views/Shared/InjectionCocineroError.cshtml
@{
        Layout = "_Layout";
}

<br />
<div class="container container-fluid">
    <p class="alert alert-danger">No tenes permisos para ingresar a la pagina solicitada</p>
    <br />
    <a class="btn btn-link" href="/Cocinero/Perfil">Volver</a>
</div>

Views/Shared/InjectionComensalError.cshtml
@{
        Layout = "_Layout";
}

<br />
<div class="container container-fluid">
    <p class="alert alert-danger">No tenes permisos para ingresar a la pagina solicitada</p>
    <br />
    <a class="btn btn-link" href="/Comensal/Index">Volver</a>
</div>

Views/Shared/InjectionDefaultError.cshtml
@{
        Layout = "_Layout";
}

<br />
<div class="container container-fluid">
    <p class="alert alert-danger">No tenes permisos para ingresar a la pagina solicitada</p>
    <br />
    <a class="btn btn-link" href="/Comensal/Index">Volver</a>
</div>

Views/Shared/_Layout.cshtml

@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />
    <title class="text-warning">@ViewData["Title"] - ekitchen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css">

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/moment.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker-standalone.css">
    <script type="text/javascript" src="~/js/bootstrap-datetimepicker.min.js"></script>
</head>
<body style="background-color:bisque">
    <header>
        <div class="sticky-top">

            <nav class="navbar navbar-light bg-light sticky-float">
                <a class="navbar-brand" href="/Default">
                    <img src="~/images/ekitchen logo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                    eKitchen
                </a>
                @if (HttpContextAccessor.HttpContext.Session.GetString("Nombre") == null)
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/Login">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/RegisterUser">Registrarse</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item text-warning">
                            Bienvenido: <strong>@HttpContextAccessor.HttpContext.Session.GetString("Nombre")</strong>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/Logout">Salir</a>
                        </li>
                    </ul>
                }
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: black; width: 100%; height: 25%; ">
        <div class="text-center p-3 text-white">
                &copy; 2021 Copyright:
                <a class="text-white" asp-area="" asp-controller="Default">Ekitchen</a>
        </div>
    </footer>
        
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutCancelarEvento.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />
    <title class="text-warning">@ViewData["Title"] - ekitchen</title>



    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css">

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>


    <script type="text/javascript" src="~/js/moment.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker-standalone.css">
    <script type="text/javascript" src="~/js/bootstrap-datetimepicker.min.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    <script>
        var myModal = new bootstrap.Modal(document.getElementById('basiceModal'), options)
    </script>
</head>
<body style="background-color:bisque">
    <header>
        <div class="sticky-top">

            <nav class="navbar navbar-light bg-light sticky-float">
                <a class="navbar-brand" href="pantalla-inicial">
                    <img src="~/images/ekitchen logo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                    eKitchen
                </a>
                @if (HttpContextAccessor.HttpContext.Session.GetString("Nombre") == null)
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/Login">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/RegisterUser">Registrarse</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            Bienvenido: <strong>@HttpContextAccessor.HttpContext.Session.GetString("Nombre")</strong>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/Logout">Salir</a>
                        </li>
                    </ul>
                }
            </nav>
        </div>
        <div class="d-flex flex-row ">
            <nav class=" p-2 navbar nav-tabs navbar-light  sticky-float">

                <ul class="nav justify-content-start">

                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Recetas">Recetas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Evento">Crear evento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Eventos">Cancelar evento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Perfil">Perfil</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: black; width: 100%; height: 25%; ">
        <div class="container">
            <div class="text-center p-3 text-white">
                &copy; 2021 Copyright:
                <a class="text-white" asp-area="" asp-controller="Cocinero">Ekitchen</a>
            </div>
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_LayoutCocinero.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />



    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css">

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>


    <script type="text/javascript" src="~/js/moment.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker-standalone.css">
    <script type="text/javascript" src="~/js/bootstrap-datetimepicker.min.js"></script>

</head>
<body style="background-color:bisque">
    <header>
        <div class="sticky-top">

            <nav class="navbar navbar-light bg-light sticky-float">
                <a class="navbar-brand" href="pantalla-inicial">
                    <img src="~/images/ekitchen logo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                    eKitchen
                </a>
                @if (HttpContextAccessor.HttpContext.Session.GetString("Nombre") == null)
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/Login">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/RegisterUser">Registrarse</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            Bienvenido: <strong>@HttpContextAccessor.HttpContext.Session.GetString("Nombre")</strong>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/Logout">Salir</a>
                        </li>
                    </ul>
                }
            </nav>
        </div>
        <div class="d-flex flex-row ">
            <nav class=" p-2 navbar nav-tabs navbar-light  sticky-float">

                <ul class="nav justify-content-start">

                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Recetas">Recetas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Evento">Crear evento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Eventos">Cancelar evento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Cocinero/Perfil">Perfil</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: black; width: 100%; height: 25%; ">
        <div class="container">
            <div class="text-center p-3 text-white">
                &copy; 2021 Copyright:
                <a class="text-white" asp-area="" asp-controller="Cocinero">Ekitchen</a>
            </div>
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_LayoutComensal.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/x-icon" href="~/images/favicon.ico" />
   
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css">

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>


    <script type="text/javascript" src="~/js/moment.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datetimepicker-standalone.css">
    <script type="text/javascript" src="~/js/bootstrap-datetimepicker.min.js"></script>
</head>
<body style="background-color:bisque">
    <header>
        <div class="sticky-top">

            <nav class="navbar navbar-light bg-light sticky-float">
                <a class="navbar-brand" href="pantalla-inicial">
                    <img src="~/images/ekitchen logo.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
                    eKitchen
                </a>
                @if (HttpContextAccessor.HttpContext.Session.GetString("Nombre") == null)
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link" href="/Login/Login">Iniciar Sesión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Login/RegisterUser">Registrarse</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            Bienvenido: <strong>@HttpContextAccessor.HttpContext.Session.GetString("Nombre")</strong>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" href="/Login/Logout">Salir</a>
                        </li>
                    </ul>
                }
            </nav>
        </div>
        <div class="d-flex flex-row ">
            <nav class=" p-2 navbar nav-tabs navbar-light  sticky-float">

                <ul class="nav justify-content-start">
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Comensal/Reserva">Reservar Evento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Comensal/Index">Mis Reservas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-info" href="/Comensal/Comentarios">Puntuar y Comentar Eventos</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: black; width: 100%; height: 25%; ">
        <div class="container">
            <div class="text-center p-3 text-white">
                &copy; 2021 Copyright:
                <a class="text-white" asp-area="" asp-controller="Comensal">Ekitchen</a>
            </div>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>